Repository denysdovhan/ha-check-weather, pull requests merged in 2024-07, with the labels that each got.

#11 fix: runtime errors
  custom_components/check_weather/binary_sensor.py
  custom_components/check_weather/config_flow.py
Labels: bug

#16 Add min/max values for temperature
  custom_components/check_weather/__init__.py
  custom_components/check_weather/binary_sensor.py
  custom_components/check_weather/config_flow.py
  custom_components/check_weather/const.py
  custom_components/check_weather/translations/en.json
  custom_components/check_weather/translations/uk.json
Labels: enhancement, breaking

#17 Add translations for attributes
  custom_components/check_weather/binary_sensor.py
  custom_components/check_weather/translations/en.json
  custom_components/check_weather/translations/uk.json
Labels: enhancement

#19 fix precipitations tipo
  custom_components/check_weather/binary_sensor.py
  custom_components/check_weather/const.py
  custom_components/check_weather/translations/en.json
Labels: bug

#20 fix: coerce floats in config flow
  custom_components/check_weather/config_flow.py
Labels: bug

#23 Update en.json
  custom_components/check_weather/translations/en.json
Labels: bug

#22 Create pl.json
  custom_components/check_weather/translations/pl.json
Labels: enhancement

#24 Add German Language
  custom_components/check_weather/translations/de.json
  readme.md
Labels: enhancement
